"""Import the five requested Radio Odeon galleries into the local site catalog."""
from pathlib import Path
from urllib.parse import urljoin, urlparse
import json
import sys
import hashlib
from concurrent.futures import ThreadPoolExecutor
from io import BytesIO
import requests
from bs4 import BeautifulSoup
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
ARTICLES = {
    'brkati-2025': 'brkati-pohod-ozavescal-o-zdravju-moskih',
    'brkati-2023': 'najbolj-brkati-pohod-v-beli-krajini',
    'brkati-2024': 'drugi-najbolj-brkati-pohod-na-mirno-goro-druzenje-zdravje-in-brki',
    'roznati-2025': 'roznati-koraki-za-zdravje-pogum-in-povezanost',
    'roznati-2024': 'roznati-koraki-v-doblicah',
}

def download_photo(job):
    url, path = job
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        data = path.read_bytes()
    else:
        response = requests.get(url, timeout=60)
        response.raise_for_status()
        if not response.headers.get('Content-Type', '').startswith('image/'):
            raise ValueError(f'Expected image: {url}')
        data = response.content
    with Image.open(BytesIO(data)) as image:
        width, height = image.size
        image.verify()
    if not path.exists():
        temporary = path.with_suffix(path.suffix + '.part')
        temporary.write_bytes(data)
        temporary.replace(path)
    return {'url': path.relative_to(ROOT / 'public').as_posix(), 'sourceUrl': url,
            'width': width, 'height': height, 'bytes': len(data),
            'sha256': hashlib.sha256(data).hexdigest()}


def import_news():
    cache = ROOT / '.cache' / 'odeon'
    cache.mkdir(parents=True, exist_ok=True)
    copy = json.loads((ROOT / 'content' / 'news-copy.json').read_text(encoding='utf-8'))
    exclusions_path = ROOT / 'content' / 'gallery-exclusions.json'
    exclusions = json.loads(exclusions_path.read_text(encoding='utf-8')) if exclusions_path.exists() else {}
    catalog = {'schemaVersion': 1, 'source': 'Radio Odeon', 'articles': []}
    for event_id, slug in ARTICLES.items():
        url = f'https://radio-odeon.com/novice/{slug}/'
        cached = cache / f'{event_id}.html'
        if not cached.exists():
            response = requests.get(url, timeout=40)
            response.raise_for_status()
            response.encoding = 'utf-8'
            cached.write_text(response.text, encoding='utf-8')
        soup = BeautifulSoup(cached.read_text(encoding='utf-8'), 'html.parser')
        area = soup.find('h1').parent.parent
        attribution = area.select_one('.article-author, .article-source')
        sources = list(dict.fromkeys(urljoin(url, a['href']) for a in area.select('a.glightbox[href]')))
        if not sources:
            raise ValueError(f'No gallery found for {event_id}')
        jobs = []
        for index, source in enumerate(sources, 1):
            # Preserve source numbering so existing local filenames remain stable.
            # Editorial exclusions must not be downloaded again on the next import.
            if source in exclusions.get(event_id, []):
                continue
            parsed = urlparse(source)
            if parsed.hostname not in ('radio-odeon.com', 'www.radio-odeon.com') or not parsed.path.startswith('/site/assets/files/'):
                raise ValueError(f'Unexpected image source: {source}')
            ext = Path(parsed.path).suffix.lower()
            if ext not in ('.jpg', '.jpeg', '.png', '.webp'):
                raise ValueError(f'Unexpected image extension: {source}')
            jobs.append((source, ROOT / 'public' / 'assets' / 'novice' / event_id / f'{index:03d}{ext}'))
        with ThreadPoolExecutor(max_workers=4) as pool:
            photos = list(pool.map(download_photo, jobs))
        for index, photo in enumerate(photos, 1):
            photo['caption'] = f"{copy[event_id]['title']} · Fotografija {index}. {copy[event_id]['photoCredit']}"
        article = {'eventId': event_id, **copy[event_id], 'sourceTitle': area.find('h1').get_text(' ', strip=True),
                   'sourceUrl': url, 'publishedAt': area.find('time')['datetime'],
                   'sourceCredit': attribution.get_text(' ', strip=True) if attribution else 'Radio Odeon',
                   'cover': photos[0]['url'], 'photos': photos}
        catalog['articles'].append(article)
        print(f'{event_id}: {len(photos)} photographs saved.', flush=True)
    catalog['articles'].sort(key=lambda a: a['publishedAt'], reverse=True)
    destination = ROOT / 'public' / 'data'
    destination.mkdir(exist_ok=True)
    payload = json.dumps(catalog, ensure_ascii=False, indent=2)
    (destination / 'news.json').write_text(payload + '\n', encoding='utf-8')
    (destination / 'news.js').write_text('/* Generated by import_odeon.py; source catalog: news.json. */\nwindow.NEWS_DATABASE = ' + payload + ';\n', encoding='utf-8')
    count = sum(len(a['photos']) for a in catalog['articles'])
    size = sum(p['bytes'] for a in catalog['articles'] for p in a['photos'])
    print(f'Catalog ready: {len(catalog["articles"])} articles, {count} photos, {size / 1024 / 1024:.1f} MiB.')

if __name__ == '__main__':
    sys.stdout.reconfigure(encoding='utf-8')
    import_news()
