"""Prepare browser-readable route data from the original local GPX files."""
import hashlib
import json
import math
from pathlib import Path
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
ROUTES = (
    ('roznati', 'Rožnati koraki', 'Roznati-koraki.gpx', '#bf4a70'),
    ('brkati', 'Brkati pohod', 'Brkati-pohod.gpx', '#3b5366'),
)


def distance(a, b):
    lat1, lon1, lat2, lon2 = map(math.radians, (a[0], a[1], b[0], b[1]))
    h = math.sin((lat2-lat1)/2)**2 + math.cos(lat1)*math.cos(lat2)*math.sin((lon2-lon1)/2)**2
    return 6371000 * 2 * math.asin(math.sqrt(min(1, max(0, h))))


def read_route(path):
    root = ET.parse(path).getroot()
    tracks = root.findall('.//{*}trkseg')
    groups = tracks or root.findall('.//{*}rte')
    tag = 'trkpt' if tracks else 'rtept'
    segments = []
    for group in groups:
        points = []
        for item in group.findall('{*}' + tag):
            lat, lon = float(item.attrib['lat']), float(item.attrib['lon'])
            if not (math.isfinite(lat) and math.isfinite(lon) and -90 <= lat <= 90 and -180 <= lon <= 180):
                raise ValueError(f'Invalid coordinates in {path.name}')
            points.append([lat, lon])
        if len(points) >= 2:
            segments.append(points)
    if not segments:
        raise ValueError(f'No usable track or route in {path.name}')
    length = sum(distance(a, b) for segment in segments for a, b in zip(segment, segment[1:]))
    return {
        'segments': segments,
        'distanceMeters': round(length, 1),
        'closed': len(segments) == 1 and distance(segments[0][0], segments[-1][-1]) < 50,
        'pointCount': sum(map(len, segments)),
        'sha256': hashlib.sha256(path.read_bytes()).hexdigest(),
    }


def main():
    routes = []
    for route_id, title, filename, color in ROUTES:
        path = ROOT / 'public' / 'assets' / 'gpx' / filename
        routes.append({'id': route_id, 'title': title, 'color': color,
                       'download': f'assets/gpx/{filename}', **read_route(path)})
    data = json.dumps({'routes': routes}, ensure_ascii=False, separators=(',', ':'))
    destination = ROOT / 'public' / 'data'
    destination.mkdir(parents=True, exist_ok=True)
    (destination / 'routes.json').write_text(data + '\n', encoding='utf-8')
    (destination / 'routes.js').write_text('/* Generated by scripts/prepare_routes.py from GPX. */\nwindow.HIKING_ROUTES = ' + data + ';\n', encoding='utf-8')
    for route in routes:
        print(f'{route["id"]}: {route["pointCount"]} points, {route["distanceMeters"]} m, closed={route["closed"]}')


if __name__ == '__main__':
    main()
